### PR TITLE
Superclass improvements

### LINKED ISSUE #160: java.lang.VerifyError: Bad return type
Hello @jbachorik,
i have on my project an error if i use btrace for performance measure.
I reproduced it, checkout:
https://github.com/mfilser/btraceVerifyError

If you are on linux run the shell script ./test.
Here is the error output:

```
Exception in thread "main" java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    btrace/test/verifyError/Persons.getPerson(Ljava/lang/String;)Lbtrace/test/verifyError/Person; @56: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'btrace/test/verifyError/Person' (from method signature)
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'btrace/test/verifyError/Persons', 'java/lang/String', long, long_2nd, long, long_2nd, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 1400 1041 b800 1737 0412 21b8 000f bb00
    0000010: 2359 2bb7 0025 3a06 2bb6 002b 9a00 0dbb
    0000020: 002d 592b b700 2e3a 0619 06b8 0017 1604
    0000030: 6541 1221 20b8 001b b0                 
  Stackmap Table:
    append_frame(@41,Long,Long,Object[#4])

        at btrace.test.verifyError.Main.<init>(Main.java:9)
        at btrace.test.verifyError.Main.main(Main.java:14)

### PR DESCRIPTION
**Pull request by jbachorik**
This patch replaces a complex and heavy approach when matching subtype based `@OnMethod` handlers of installing special callback into each newly loaded class' static initializer with walking the class hierarchy manually using the associated classloader.

A similar trick may be used for getting common ancestor for ASM when computing frames - fixes #160
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826178%22%2C%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826185%22%2C%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826192%22%2C%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826260%22%2C%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826261%22%2C%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826262%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20658ff7c852c49d3b892cc2895370074cf5893e00%20src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java%2072%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826185%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Call%20%60DebugSupport.warning%28e%29%60%20instead.%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A25%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A34%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java%3AL28-114%22%7D%2C%20%22Pull%20658ff7c852c49d3b892cc2895370074cf5893e00%20src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java%2048%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826178%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Remove%20debugging%20output%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A24%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A34%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java%3AL28-114%22%7D%2C%20%22Pull%20658ff7c852c49d3b892cc2895370074cf5893e00%20src/test/traces/OnMethodSubclassTest.java%202%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jbachorik/btrace/pull/195%23discussion_r52826192%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Copyright%202016%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A26%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-complete%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222016-02-13T10%3A34%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/738413%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jbachorik%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/test/traces/OnMethodSubclassTest.java%3AL1-45%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-Pull 658ff7c852c49d3b892cc2895370074cf5893e00 src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java 48'></a> &nbsp;<b><a href='https://github.com/jbachorik/btrace/pull/195#discussion_r52826178'>File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java:L28-114</a></b>
- <a href='https://github.com/jbachorik'></a> Remove debugging output
- [x] <a href='#crh-comment-Pull 658ff7c852c49d3b892cc2895370074cf5893e00 src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java 72'></a> &nbsp;<b><a href='https://github.com/jbachorik/btrace/pull/195#discussion_r52826185'>File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java:L28-114</a></b>
- <a href='https://github.com/jbachorik'></a> Call `DebugSupport.warning(e)` instead.
- [x] <a href='#crh-comment-Pull 658ff7c852c49d3b892cc2895370074cf5893e00 src/test/traces/OnMethodSubclassTest.java 2'></a> &nbsp;<b><a href='https://github.com/jbachorik/btrace/pull/195#discussion_r52826192'>File: src/test/traces/OnMethodSubclassTest.java:L1-45</a></b>
- <a href='https://github.com/jbachorik'></a> Copyright 2016

<a href='https://www.codereviewhub.com/jbachorik/btrace/pull/195?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jbachorik/btrace/pull/195?approve=1'></a>&nbsp;<a href='https://github.com/jbachorik/btrace/pull/195'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by jbachorik** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jbachorik/btrace/pull/195'>Refresh</a>.<a href='#crh-update-none'></a>

File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java [hunk 1]
```diff
@@ -28,64 +28,86 @@
...
+    * @param cl the associated classloader
+    * @param type the type to compute the hierarchy closure for
+    * @param closure the list to store the closure in
+    */
+    public static void collectHierarchyClosure(ClassLoader cl, String type, List<String> closure) {
+        if (type == null || type.equals(JAVA_LANG_OBJECT)) {
+           return;
+        }
+        try {
+           System.err.println("*** getting hierarchy for " + type);
```
Comment (jbachorik) [inline src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java]: Remove debugging output

File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java [hunk 2]
```diff
@@ -28,64 +28,86 @@
...
+                    collectHierarchyClosure(cl, superType, closure);
                 }
-                return clz != null;
             }
-        }
-
-        private static final CheckingClassLoader CHECKING_CL =
-                new CheckingClassLoader(ClassWriter.class.getClassLoader());
+       } catch (IOException e) {
+            e.printStackTrace();
```
Comment (jbachorik) [inline src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java]: Call `DebugSupport.warning(e)` instead.

File: src/test/traces/OnMethodSubclassTest.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
+/*
+ * Copyright (c) 2008, 2015, Oracle and/or its affiliates. All rights reserved.
```
Comment (jbachorik) [inline src/test/traces/OnMethodSubclassTest.java]: Copyright 2016

File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java (hunk 2 above)
Comment (jbachorik) [inline src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java]: :+1:<a href='#crh-update-none'></a>

File: src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java (hunk 1 above)
Comment (jbachorik) [inline src/share/classes/com/sun/btrace/runtime/InstrumentUtils.java]: :+1:<a href='#crh-update-none'></a>

File: src/test/traces/OnMethodSubclassTest.java (hunk 3 above)
Comment (jbachorik) [inline src/test/traces/OnMethodSubclassTest.java]: :+1:<a href='#crh-update-complete'></a>
